UPDATE xmall.goods SET name = '枫糖奶酪芝士饼', description = '甜点与咸香的完美融合。采用新鲜奶油芝士与枫糖的经典搭配，香浓的芝士与枫糖的甜香完美结合，口感层次丰富。饼皮酥脆，奶香十足，适合早晨搭配一杯热咖啡或茶享用。
', no = 'g1001', price = 15.00, discount = 0.9, store = 996, praise = 4, sales = 4, category_id = 1, imgs = '["http://localhost:9999/files/good1.jpg"]', create_time = '2025-07-7 07:32:22', recommend = 1 WHERE id = 1;
UPDATE xmall.goods SET name = '脆皮核桃面包', description = '脆皮核桃面包外层酥脆，内里充满了浓郁的核桃香气。采用优质核桃，配以松软的面包皮，使得每一口都充满了香脆和奶香的完美融合。适合任何时刻享用，尤其是作为早餐或下午茶的小点心。', no = 'g1002', price = 15.00, discount = 1, store = 97, praise = 0, sales = 3, category_id = 4, imgs = '["http://localhost:9999/files/good2.jpg"]', create_time = '2025-07-7 07:32:22', recommend = 1 WHERE id = 2;
UPDATE xmall.goods SET name = '奶酥核桃仁可颂片', description = '可颂片酥皮香脆，内层夹杂了香浓的坚果与核桃仁。每一口都能感受到坚果的自然香气，搭配可颂独有的松脆口感，令人回味无穷。它是一款极富营养且口感丰富的糕点，非常适合做为早餐或下午茶点心。', no = 'g1002', price = 15.00, discount = 0.5, store = 97, praise = 0, sales = 3, category_id = 1, imgs = '["http://localhost:9999/files/good3.jpg"]', create_time = '2025-07-7 07:32:22', recommend = 1 WHERE id = 3;
UPDATE xmall.goods SET name = '芝士洋葱玉米烙', description = '面包的外皮松软，里面填充了醇厚的奶酪与洋葱，玉米的香甜味为这款面包增添了一丝自然的甜味。无论是单独享用，还是搭配其他食品，这款面包都是完美的选择。', no = 'g1004', price = 15.50, discount = 0.9, store = 994, praise = 0, sales = 6, category_id = 1, imgs = '["http://localhost:9999/files/good4.jpg"]', create_time = '2025-07-7 07:32:22', recommend = 1 WHERE id = 4;
UPDATE xmall.goods SET name = '脆香核桃马里奥', description = '脆香核桃马里奥以浓厚的核桃香气为主打，面包外层经过特别的烘焙工艺，使其表面更加酥脆，内里柔软。用料讲究，搭配独特的口感，让人一口接一口，停不下来。', no = 'g1006', price = 15.00, discount = 0.47, store = 998, praise = 0, sales = 2, category_id = 1, imgs = '["http://localhost:9999/files/good5.jpg"]', create_time = '2025-07-7 07:32:22', recommend = 1 WHERE id = 5;
UPDATE xmall.goods SET name = '核桃红豆丹麦包', description = '丹麦包的外层脆而不硬，内里含有细腻的红豆馅和香脆的核桃。口感层次丰富，甜中带咸，既能感受到红豆的细腻，又能享受核桃的香脆，带给你与众不同的美味体验。', no = 'g1006', price = 15.00, discount = 1, store = 1, praise = 0, sales = 0, category_id = 1, imgs = '["http://localhost:9999/files/good6.jpg"]', create_time = '2025-07-7 07:32:22', recommend = null WHERE id = 6;
UPDATE xmall.goods SET name = '奶油瀑布包', description = '奶油瀑布包是由柔软的面包皮包裹着香浓的奶油，口感绵密丰富。每一口都带有浓郁的奶香，适合任何时刻的享用。尤其在早晨，配上一杯牛奶，是一天的完美开始。', no = 'g1006', price = 15.00, discount = 1, store = 0, praise = 0, sales = 1, category_id = 1, imgs = '["http://localhost:9999/files/good7.jpg"]', create_time = '2025-07-7 07:32:22', recommend = null WHERE id = 7;
UPDATE xmall.goods SET name = '酸奶菠萝吐司', description = '酸奶菠萝吐司选用了酸奶作为原料，使面包更加松软且富有弹性。每一口都能感受到酸奶的清新与微酸，搭配面包的柔软，口感极佳，是非常健康又美味的早餐选择。', no = 'g1006', price = 15.00, discount = 1, store = 1, praise = 0, sales = 0, category_id = 1, imgs = '["http://localhost:9999/files/good8.jpg"]', create_time = '2025-07-7 07:32:22', recommend = null WHERE id = 8;
UPDATE xmall.goods SET name = '乳酪桑葚核桃包', description = '乳酪桑葚核桃包将乳酪的醇香与桑葚的酸甜完美融合，外脆内软，香气扑鼻。每一口都能够感受到酸甜与奶香的对比，让你在享受美味的同时感受到桑葚的清新与奶酪的丝滑。', no = 'g1006', price = 15.00, discount = 1, store = 1, praise = 0, sales = 0, category_id = 1, imgs = '["http://localhost:9999/files/good9.jpg"]', create_time = '2025-07-7 07:32:22', recommend = null WHERE id = 9;
UPDATE xmall.goods SET name = '藜麦果仁杂粮包', description = '精选丰富的杂粮与新鲜果仁，面包外层脆而不硬，内里夹杂了多种坚果和葡萄的清新果香。每一口都充满了果香和坚果的香脆，是一款既健康又美味的选择。', no = 'g1006', price = 15.00, discount = 1, store = 1, praise = 0, sales = 0, category_id = 1, imgs = '["http://localhost:9999/files/good10.jpg"]', create_time = '2025-07-7 07:32:22', recommend = null WHERE id = 10;
UPDATE xmall.goods SET name = '芝芝红豆核桃包', description = '芝士红豆核桃包带有浓厚的奶香，结合了甜美的红豆和香脆的核桃，外皮松软，内馅丰富，奶香十足。口感层次丰富，甜中带咸，适合任何时刻享用。', no = 'g1006', price = 15.00, discount = 1, store = 1, praise = 0, sales = 0, category_id = 1, imgs = '["http://localhost:9999/files/good11.jpg"]', create_time = '2025-07-7 07:32:22', recommend = null WHERE id = 11;
UPDATE xmall.goods SET name = '蔓越莓奶香圈', description = '奶香圈将葡萄和莓果的酸甜与浓郁的奶香相结合，面包圈外层松软，内里充满了莓果的清新味道。非常适合作为早餐或下午茶享用，口感独特，令人回味。', no = 'g1006', price = 15.00, discount = 1, store = 1, praise = 0, sales = 0, category_id = 1, imgs = '["http://localhost:9999/files/good12.jpg"]', create_time = '2025-07-7 07:32:22', recommend = null WHERE id = 12;
UPDATE xmall.goods SET name = '双莓核桃卷卷棒', description = '双莓核桃卷香棒选用了双种莓果和核桃，酸甜的莓果与香脆的核桃搭配起来非常美味。面包外皮酥脆，内馅松软，口感丰富，既能享受果香，也能品味到坚果的脆香。', no = 'g1006', price = 15.00, discount = 1, store = 1, praise = 0, sales = 0, category_id = 1, imgs = '["http://localhost:9999/files/good13.jpg"]', create_time = '2025-07-7 07:32:22', recommend = null WHERE id = 13;
UPDATE xmall.goods SET name = '蔓越莓切片面包', description = '蔓越莓切片面包将莓果的清新酸甜与面包的松软结合，每一片都带有丰富的水果香气。适合在任何时刻切片享用，作为零食或搭配饮品都非常合适。', no = 'g1006', price = 15.00, discount = 1, store = 1, praise = 0, sales = 0, category_id = 1, imgs = '["http://localhost:9999/files/good14.jpg"]', create_time = '2025-07-7 07:32:22', recommend = null WHERE id = 14;
